"""ChunkingService 单元测试

测试两阶段切分逻辑：
- Stage 1: MarkdownHeaderTextSplitter 按标题切分
- Stage 2: RecursiveCharacterTextSplitter 对过长块二次切分

**Feature: rag-simplification**
**Validates: Requirements 3.1, 3.2, 3.3, 3.4**
"""

import sys
from pathlib import Path

# 直接添加 services/document 目录到路径，避免触发整个 services 包的导入
backend_dir = Path(__file__).parent.parent
sys.path.insert(0, str(backend_dir / "services" / "document"))
sys.path.insert(0, str(backend_dir))

import pytest

# 直接导入模块文件
import importlib.util
spec = importlib.util.spec_from_file_location(
    "chunking_service", 
    backend_dir / "services" / "document" / "chunking_service.py"
)
chunking_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(chunking_module)
ChunkingService = chunking_module.ChunkingService


class TestChunkingService:
    """ChunkingService 测试类"""
    
    @pytest.fixture
    def chunker(self):
        """创建 ChunkingService 实例"""
        return ChunkingService()
    
    # ==================== 基础功能测试 ====================
    
    def test_chunk_text_empty_input(self, chunker):
        """测试空输入返回空列表"""
        result = chunker.chunk_text("")
        assert result == []
        
        result = chunker.chunk_text("   ")
        assert result == []
        
        result = chunker.chunk_text(None)
        assert result == []
    
    def test_chunk_text_returns_list(self, chunker, sample_markdown_with_headers):
        """测试返回值是列表类型"""
        result = chunker.chunk_text(sample_markdown_with_headers)
        assert isinstance(result, list)
        assert len(result) > 0
    
    def test_chunk_structure(self, chunker, sample_markdown_with_headers):
        """测试每个 chunk 包含必要字段"""
        result = chunker.chunk_text(sample_markdown_with_headers)
        
        for chunk in result:
            assert 'content' in chunk
            assert 'heading_path' in chunk
            assert isinstance(chunk['content'], str)
            assert isinstance(chunk['heading_path'], list)
    
    # ==================== Property 5: Chunk size constraint ====================
    # **Feature: rag-simplification, Property 5: Chunk size constraint**
    
    def test_chunk_size_constraint(self, chunker, sample_long_markdown):
        """
        Property 5: Chunk size constraint
        
        *For any* TEXT chunk generated by ChunkingService, 
        the length of content SHALL be less than or equal to 512 characters
        (allowing for overlap boundary cases up to 562 characters).
        
        **Validates: Requirements 3.2**
        """
        result = chunker.chunk_text(sample_long_markdown)
        
        max_allowed = 512 + 50  # chunk_size + chunk_overlap
        
        for chunk in result:
            content_len = len(chunk['content'])
            assert content_len <= max_allowed, \
                f"Chunk 长度 {content_len} 超过最大允许值 {max_allowed}"
    
    # ==================== Property 6: Heading path preservation ====================
    # **Feature: rag-simplification, Property 6: Heading path preservation**
    
    def test_heading_path_preservation(self, chunker, sample_markdown_with_headers):
        """
        Property 6: Heading path preservation
        
        *For any* TEXT chunk generated from Markdown containing headers,
        the metadata SHALL contain a heading_path field that is a non-empty list of strings.
        
        **Validates: Requirements 3.3**
        """
        result = chunker.chunk_text(sample_markdown_with_headers)
        
        # 至少有一些 chunk 应该有非空的 heading_path
        chunks_with_headers = [c for c in result if c['heading_path']]
        assert len(chunks_with_headers) > 0, "应该有 chunk 保留了标题路径"
        
        for chunk in chunks_with_headers:
            assert isinstance(chunk['heading_path'], list)
            for header in chunk['heading_path']:
                assert isinstance(header, str)
                assert len(header) > 0
    
    # ==================== Property 7: Minimum chunk length ====================
    # **Feature: rag-simplification, Property 7: Minimum chunk length**
    
    def test_minimum_chunk_length(self, chunker, sample_short_chunks_markdown):
        """
        Property 7: Minimum chunk length
        
        *For any* chunk generated by ChunkingService,
        the length of content SHALL be greater than or equal to 20 characters.
        
        **Validates: Requirements 3.4**
        """
        result = chunker.chunk_text(sample_short_chunks_markdown)
        
        for chunk in result:
            content_len = len(chunk['content'])
            assert content_len >= 20, \
                f"Chunk 长度 {content_len} 小于最小值 20: '{chunk['content'][:50]}...'"
    
    # ==================== 标题切分测试 ====================
    
    def test_header_splitting(self, chunker, sample_markdown_with_headers):
        """测试按 Markdown 标题切分"""
        result = chunker.chunk_text(sample_markdown_with_headers)
        
        # 检查是否有多个 chunk（说明进行了切分）
        assert len(result) > 1, "应该切分成多个 chunk"
        
        # 检查 heading_path 是否正确构建
        heading_paths = [c['heading_path'] for c in result]
        
        # 应该有不同层级的标题
        all_headers = []
        for path in heading_paths:
            all_headers.extend(path)
        
        # 验证标题被正确提取
        assert any('引言' in h or '第一章' in h for h in all_headers), \
            "应该包含第一章相关标题"
    
    # ==================== 二次切分测试 ====================
    
    def test_long_text_secondary_split(self, chunker, sample_long_markdown):
        """测试长文本的二次切分"""
        result = chunker.chunk_text(sample_long_markdown)
        
        # 长文本应该被切分成多个 chunk
        assert len(result) > 1, "长文本应该被切分成多个 chunk"
        
        # 所有 chunk 都应该在大小限制内
        for chunk in result:
            assert len(chunk['content']) <= 562  # 512 + 50 overlap
    
    # ==================== 降级方案测试 ====================
    
    def test_simple_chunk_fallback(self, chunker):
        """测试简单切分降级方案"""
        text = "这是一段测试文本。" * 50  # 约 450 字符
        
        result = chunker._simple_chunk(text)
        
        assert isinstance(result, list)
        for chunk in result:
            assert 'content' in chunk
            assert 'heading_path' in chunk
            assert chunk['heading_path'] == []  # 简单切分没有标题路径
    
    def test_simple_chunk_respects_min_length(self, chunker):
        """测试简单切分也遵守最小长度限制"""
        text = "短\n" * 10 + "这是一段足够长的文本内容，应该被保留。" * 5
        
        result = chunker._simple_chunk(text)
        
        for chunk in result:
            assert len(chunk['content']) >= 20


class TestChunkingServiceEdgeCases:
    """边界情况测试"""
    
    @pytest.fixture
    def chunker(self):
        return ChunkingService()
    
    def test_no_headers_markdown(self, chunker):
        """测试没有标题的 Markdown"""
        text = "这是一段没有任何标题的纯文本内容。" * 10
        
        result = chunker.chunk_text(text)
        
        assert len(result) >= 1
        for chunk in result:
            # 没有标题时，heading_path 应该为空列表
            assert chunk['heading_path'] == []
    
    def test_only_headers_markdown(self, chunker):
        """测试只有标题没有内容的 Markdown"""
        text = """# 标题1
## 标题2
### 标题3
"""
        result = chunker.chunk_text(text)
        
        # 由于内容太短，可能被过滤掉
        # 这是预期行为
        for chunk in result:
            assert len(chunk['content']) >= 20
    
    def test_deep_nested_headers(self, chunker):
        """测试深层嵌套标题"""
        text = """# H1
## H2
### H3
#### H4
##### H5
###### H6

这是最深层级的内容，应该保留完整的标题路径。
"""
        result = chunker.chunk_text(text)
        
        # 检查是否有 chunk 保留了多层标题
        if result:
            max_depth = max(len(c['heading_path']) for c in result)
            assert max_depth >= 1, "应该保留至少一层标题"
    
    def test_chinese_content(self, chunker):
        """测试中文内容处理"""
        text = """# 中文标题

这是一段中文内容，用于测试中文字符的正确处理。
包含标点符号：，。！？；：""''
以及数字：12345

## 第二节

更多中文内容在这里。
"""
        result = chunker.chunk_text(text)
        
        assert len(result) >= 1
        for chunk in result:
            assert isinstance(chunk['content'], str)
            # 验证中文内容被正确保留
            assert any('\u4e00' <= c <= '\u9fff' for c in chunk['content']), \
                "应该包含中文字符"
